default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: pg
  username: postgres
  timeout: 5000

development:
  <<: *default
  database: graphql_todo_development

test:
  <<: *default
  database: graphql_todo_test

production:
  <<: *default
  database: graphql_todo_production
  username: postgres
  password:

